Dailyonly option
m-lab/etl-gardener pull request #352
Opened 2021-12-15 01:39 UTC by gfr10598

This introduces a dailyOnly option, that suppresses reprocessing of old data for a datatype.  It will, of course, cause alerts to fire.

This is currently built on top of a change to provide faster build times, but that will be merged first.

2021-12-15 15:13 UTC, stephen-soltesz reviewed
I love this idea -- I fear we may encounter the same issue I found in the dataset updates to gardener https://github.com/m-lab/etl-gardener/pull/350

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/352#-:-Mqyb-w7-FHBkJhzGQNy:buu8ldj)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[tracker/job.go, line 39 at r1](https://reviewable.io/reviews/m-lab/etl-gardener/352#-Mqy_z5-BzOOtl31SbHn:-Mqy_z5-BzOOtl31SbHo:b-km0dti) ([raw file](https://github.com/m-lab/etl-gardener/blob/20d187095fdaff01b53274fdada41b973f0008ac/tracker/job.go#L39)):*
> ```Go
> 
> 	// Alternatively, export and use a json tag?
> 	dailyOnly bool // Not included in json interface.
> ```

Do private struct field values count when using structs as map keys? If so, this may cause the same issue I encountered with the datasets patch to only gardener. The value sent to the etl worker and sent back on updates will be different by this value. I fear any change to this struct will require an update to etl at the same time in the current system.


<!-- Sent from Reviewable.io -->

2021-12-15 17:53 UTC, gfr10598 reviewed
Yup.  Already addressed I think.  Deploying to sandbox to see how it behaves after change.

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/352#-:-MqzDMRl1ofpw5g4H55H:b-9qfvc3)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[tracker/job.go, line 39 at r1](https://reviewable.io/reviews/m-lab/etl-gardener/352#-Mqy_z5-BzOOtl31SbHn:-MqzDEZj4ppVsn_zTxDN:b-ci9me9) ([raw file](https://github.com/m-lab/etl-gardener/blob/20d187095fdaff01b53274fdada41b973f0008ac/tracker/job.go#L39)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Do private struct field values count when using structs as map keys? If so, this may cause the same issue I encountered with the datasets patch to only gardener. The value sent to the etl worker and sent back on updates will be different by this value. I fear any change to this struct will require an update to etl at the same time in the current system.
</blockquote></details>

Yes they do.  You are correct and I had to add code to clear this field for key use.


<!-- Sent from Reviewable.io -->

2021-12-15 17:54 UTC, gfr10598 reviewed
I'll separate out the config change and push.  Didn't mean to mix them.

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/352#-:-MqzDjId8ErnxPi3Mx4p:b8r728o)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr)



<!-- Sent from Reviewable.io -->

2021-12-15 18:21 UTC, gfr10598 commented
Ok - deploying to sandbox with one extra commit to make ndt7 dailyOnly.  Unfortunately, we won't see if it works correctly until tomorrow morning.

The branch now has just the code changes, without config change.

2021-12-15 18:22 UTC, gfr10598 commented
Argh - looks like I screwed that up and lost the code changes when I removed the last commit.  Fixing now.

2021-12-16 23:23 UTC, stephen-soltesz requested changes
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/352)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @cristinaleonr and @gfr10598)

___
*[job-service/job-service.go, line 162 at r2](https://reviewable.io/reviews/m-lab/etl-gardener/352#-Mr4XsIH3PEikTjPSMUH:-Mr4XsIH3PEikTjPSMUI:b2s2ria) ([raw file](https://github.com/m-lab/etl-gardener/blob/00e29fcc3176a761bbd6f11948217a46bdf7763b/job-service/job-service.go#L162)):*
> ```Go
> 	}
> 
> 	for i := 0; i < 3; i++ {
> ```

What is this?
___
*[tracker/tracker.go, line 144 at r3](https://reviewable.io/reviews/m-lab/etl-gardener/352#-Mr4Y8eYAa5IkNUKb0yS:-Mr4Y8eYAa5IkNUKb0yT:bcg8t22) ([raw file](https://github.com/m-lab/etl-gardener/blob/dd3f12555e5c7d62c950d192be1a446f3a45600d/tracker/tracker.go#L144)):*
> ```Go
> // field shares the slice objects with the JobMap.
> func (tr *Tracker) GetStatus(job Job) (Status, error) {
> 	job.dailyOnly = false // For the status, we always clear this field.
> ```

We spoke in person about this pattern. Because we would not want to repeat this pattern with additional novel fields (e.g. those from the dataset PR #349 ) a better approach will be to define a simple `Job.Key()` method and rather than using the entire `Job` struct as the key, we can use the key returned by this new method. This will also provide a way for new field introduction to the config & job structures relevant to Gardener but unknown to the ETL worker without having to update the ETL worker.


<!-- Sent from Reviewable.io -->

2021-12-21 14:47 UTC, gfr10598 reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/352)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @cristinaleonr and @stephen-soltesz)

___
*[job-service/job-service.go, line 162 at r2](https://reviewable.io/reviews/m-lab/etl-gardener/352#-Mr4XsIH3PEikTjPSMUH:-Mr4twpnEtDEEfLyvRe6:b20gyza) ([raw file](https://github.com/m-lab/etl-gardener/blob/00e29fcc3176a761bbd6f11948217a46bdf7763b/job-service/job-service.go#L162)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

What is this?
</blockquote></details>

I've refactored and tweaked the code a bit, and added a more extensive comment.
___
*[tracker/tracker.go, line 144 at r3](https://reviewable.io/reviews/m-lab/etl-gardener/352#-Mr4Y8eYAa5IkNUKb0yS:-Mr4u3Sx-NLEGIchrkJN:b-896fix) ([raw file](https://github.com/m-lab/etl-gardener/blob/dd3f12555e5c7d62c950d192be1a446f3a45600d/tracker/tracker.go#L144)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

We spoke in person about this pattern. Because we would not want to repeat this pattern with additional novel fields (e.g. those from the dataset PR #349 ) a better approach will be to define a simple `Job.Key()` method and rather than using the entire `Job` struct as the key, we can use the key returned by this new method. This will also provide a way for new field introduction to the config & job structures relevant to Gardener but unknown to the ETL worker without having to update the ETL worker.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-21 18:01 UTC, stephen-soltesz requested changes
Thank you for the changes to add a `Job.Key` this looks very promising. I have a few more comments that I hope you'll agree will make the over all interface simpler and easier to evolve over time.

> Reviewed 1 of 6 files at r1, 1 of 1 files at r2, 1 of 3 files at r4, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/352#-:-MrT7sBe-IaJcef9qTuB:bawd4dz)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @cristinaleonr and @gfr10598)

___
*[config/config.go, line 35 at r8](https://reviewable.io/reviews/m-lab/etl-gardener/352#-MrT8cNd0TwSc-PdPoEK:-MrT8cNd0TwSc-PdPoEL:b-5wiylj) ([raw file](https://github.com/m-lab/etl-gardener/blob/a34d2eed29282e78b889b2d3cbb57ffcc106be16/config/config.go#L35)):*
> ```Go
> 	Filter     string `yaml:"filter"`
> 	Target     string `yaml:"target"`
> 	DailyOnly  bool   `yaml:"dailyOnly"`
> ```

nit: please don't mix camel and snake case field names.
___
*[job-service/job-service.go, line 167 at r8](https://reviewable.io/reviews/m-lab/etl-gardener/352#-MrSWxcX3k6zbxlqJmm8:-MrSWxcX3k6zbxlqJmm9:bn9hy65) ([raw file](https://github.com/m-lab/etl-gardener/blob/a34d2eed29282e78b889b2d3cbb57ffcc106be16/job-service/job-service.go#L167)):*
> ```Go
> 	// for a given date, we check for these conditions, and skip the job if appropriate.
> 	// If first job isn't suitable, we check up to len(jobSpecs) to try to find one.
> 	for i := 0; i < len(svc.jobSpecs); i++ {
> ```

Since `i` is not used, I find this counter intuitive. What do you think of naming the index variable `attempts` to help self-describe the loop's goal?

```
for attempts := 0; attempts < len(svc.JobSpecs); attempts++ {
   ...
}
```
___
*[job-service/job-service.go, line 222 at r8](https://reviewable.io/reviews/m-lab/etl-gardener/352#-MrT0GddEsdZD99WgLn0:-MrT0Gde-XO9nAhYTeiP:b1thoum) ([raw file](https://github.com/m-lab/etl-gardener/blob/a34d2eed29282e78b889b2d3cbb57ffcc106be16/job-service/job-service.go#L222)):*
> ```Go
> 
> 	// Check for empty job (no job found with files and !dailyOnly)
> 	if job.Date.Equal(time.Time{}) {
> ```

Given the choice to use literals rather than pointers throughout, would having an `IsEmpty()` method help? Or, NextJob could return a bool for `ok` or not.
___
*[state/state.go, line 26 at r8](https://reviewable.io/reviews/m-lab/etl-gardener/352#-MrSyyiG8JIZ6c-yIw5Z:-MrSyKmXA2tTqEHvoAgf:bxeryme) ([raw file](https://github.com/m-lab/etl-gardener/blob/a34d2eed29282e78b889b2d3cbb57ffcc106be16/state/state.go#L26)):*
> ```Go
> // This function allows independence from etl repo.
> // See etl/etl/globals.go for etl mappings.
> func tableName(dir string) string {
> ```

Please add TODO to eliminate directory translations like this one. Otherwise this invites additional ones in the future. Uniform names should make this unnecessary in the future, and possible to eliminate with a rename in GCS one day.
___
*[tracker/job.go, line 38 at r8](https://reviewable.io/reviews/m-lab/etl-gardener/352#-MrSzWjm9dhCZB5Yek7G:-MrSzWjm9dhCZB5Yek7H:by52a4w) ([raw file](https://github.com/m-lab/etl-gardener/blob/a34d2eed29282e78b889b2d3cbb57ffcc106be16/tracker/job.go#L38)):*
> ```Go
> 	Filter string `json:",omitempty"`
> 
> 	// Alternatively, export and use a json tag?
> ```

Let's answer this question.

IIUC, the interface used by the ETL worker and the "/job" and "/update" handlers is the JSON marshaled Job object.

We can specifically tell the `json` package to ignore this field using `json:"-"`. This could clearly indicate that it is not part of the Parser/Gardener interface. Also, it would allow us to keep the field public for use within Gardener without needing the get/set methods, it can just be a field reference.
___
*[tracker/job.go, line 47 at r8](https://reviewable.io/reviews/m-lab/etl-gardener/352#-MrT5hP05Ts6GhhJ5lYX:-MrT5hP05Ts6GhhJ5lYY:b-1130wh) ([raw file](https://github.com/m-lab/etl-gardener/blob/a34d2eed29282e78b889b2d3cbb57ffcc106be16/tracker/job.go#L47)):*
> ```Go
> // Since this is pass by value, a new copy is returned.
> func (j Job) Key() JobKey {
> 	j.dailyOnly = false
> ```

What are the trade-offs you see for overwriting fields we want to omit (and for every new field we add like PR #350 ) vs affirmatively selecting only the fields we want, e.g.

```
func (j Job) Key() JobKey {
  return Job{
    	Bucket: j.Bucket,
	Experiment: j.Experiment,
	Datatype: j.Datatype,
	Date: j.Date,
  } 
}
```

I'm imagining this allows us to add new fields to the Job struct & configuration without revising the JobKey definition.


<!-- Sent from Reviewable.io -->

2021-12-29 01:49 UTC, gfr10598 reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/352)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @cristinaleonr and @stephen-soltesz)

___
*[config/config.go, line 35 at r8](https://reviewable.io/reviews/m-lab/etl-gardener/352#-MrT8cNd0TwSc-PdPoEK:-Mry-PhW6QLxl2oarADL:b-896fjx) ([raw file](https://github.com/m-lab/etl-gardener/blob/a34d2eed29282e78b889b2d3cbb57ffcc106be16/config/config.go#L35)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

nit: please don't mix camel and snake case field names.
</blockquote></details>

Done
___
*[job-service/job-service.go, line 167 at r8](https://reviewable.io/reviews/m-lab/etl-gardener/352#-MrSWxcX3k6zbxlqJmm8:-Mry_m_x2pBO90hgl7vN:b-896fix) ([raw file](https://github.com/m-lab/etl-gardener/blob/a34d2eed29282e78b889b2d3cbb57ffcc106be16/job-service/job-service.go#L167)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Since `i` is not used, I find this counter intuitive. What do you think of naming the index variable `attempts` to help self-describe the loop's goal?

```
for attempts := 0; attempts < len(svc.JobSpecs); attempts++ {
   ...
}
```

</blockquote></details>

Done.
___
*[job-service/job-service.go, line 222 at r8](https://reviewable.io/reviews/m-lab/etl-gardener/352#-MrT0GddEsdZD99WgLn0:-Mry_k9ZBalZrPuAiJJg:b-896fix) ([raw file](https://github.com/m-lab/etl-gardener/blob/a34d2eed29282e78b889b2d3cbb57ffcc106be16/job-service/job-service.go#L222)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Given the choice to use literals rather than pointers throughout, would having an `IsEmpty()` method help? Or, NextJob could return a bool for `ok` or not.
</blockquote></details>

Done.
___
*[state/state.go, line 26 at r8](https://reviewable.io/reviews/m-lab/etl-gardener/352#-MrSyyiG8JIZ6c-yIw5Z:-MrxyKL-58LUCE-CHcQ9:b-896fix) ([raw file](https://github.com/m-lab/etl-gardener/blob/a34d2eed29282e78b889b2d3cbb57ffcc106be16/state/state.go#L26)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please add TODO to eliminate directory translations like this one. Otherwise this invites additional ones in the future. Uniform names should make this unnecessary in the future, and possible to eliminate with a rename in GCS one day.
</blockquote></details>

Done.
___
*[tracker/job.go, line 38 at r8](https://reviewable.io/reviews/m-lab/etl-gardener/352#-MrSzWjm9dhCZB5Yek7G:-MrxzhHB2Masee_eays3:b-896fix) ([raw file](https://github.com/m-lab/etl-gardener/blob/a34d2eed29282e78b889b2d3cbb57ffcc106be16/tracker/job.go#L38)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Let's answer this question.

IIUC, the interface used by the ETL worker and the "/job" and "/update" handlers is the JSON marshaled Job object.

We can specifically tell the `json` package to ignore this field using `json:"-"`. This could clearly indicate that it is not part of the Parser/Gardener interface. Also, it would allow us to keep the field public for use within Gardener without needing the get/set methods, it can just be a field reference.
</blockquote></details>

Done.
___
*[tracker/job.go, line 47 at r8](https://reviewable.io/reviews/m-lab/etl-gardener/352#-MrT5hP05Ts6GhhJ5lYX:-Mry-6bj-ZVj-6agInNJ:b-qmg9ag) ([raw file](https://github.com/m-lab/etl-gardener/blob/a34d2eed29282e78b889b2d3cbb57ffcc106be16/tracker/job.go#L47)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

What are the trade-offs you see for overwriting fields we want to omit (and for every new field we add like PR #350 ) vs affirmatively selecting only the fields we want, e.g.

```
func (j Job) Key() JobKey {
  return Job{
    	Bucket: j.Bucket,
	Experiment: j.Experiment,
	Datatype: j.Datatype,
	Date: j.Date,
  } 
}
```

I'm imagining this allows us to add new fields to the Job struct & configuration without revising the JobKey definition.
</blockquote></details>

This is better.  Updated.


<!-- Sent from Reviewable.io -->

2022-01-04 15:58 UTC, stephen-soltesz approved these changes
Thank you for the updates! This <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

One remaining nit.

> Reviewed 5 of 6 files at r9.
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/352#-:-Ms_o07-236DebVyMMom:b-twxzog)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @cristinaleonr and @gfr10598)

___
*[job-service/job-service.go, line 164 at r9](https://reviewable.io/reviews/m-lab/etl-gardener/352#-Ms_mhtW5yTU_7sfTcIy:-Ms_mhtW5yTU_7sfTcIz:b2me1ey) ([raw file](https://github.com/m-lab/etl-gardener/blob/23818a81b6b004b3e3a62b294e07f2fb3b441d97/job-service/job-service.go#L164)):*
> ```Go
> 	}
> 
> 	// Since some jobs may be configured as dailyOnly, or have no files
> ```

nit: now that this is a public field, prefer either the literal name `DailyOnly` or just english description "daily only".

(please do this throughout - I noticed other instances of references to `dailyOnly` too)


<!-- Sent from Reviewable.io -->

2022-01-06 16:03 UTC, stephen-soltesz commented
@gfr10598 will you have a chance to complete this today? several PRs would be helped by this change #359 , #350 and more to come.

2022-01-10 15:17 UTC, stephen-soltesz commented
Hmm, I think I discovered that this approach won't quite work as I imagined for https://github.com/m-lab/etl-gardener/pull/350 -- the job keys are used as the actual jobs by other parts of the gardener system, so some state is lost. Modifications are getting harder to reason about and coordinate on without an architectural design. I'd like to help create that.

2022-07-10 22:00 UTC, stephen-soltesz commented
Obsolete by:
* https://github.com/m-lab/etl-gardener/pull/388

2022-07-10 22:00 UTC, closed without merging